apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse-web
  namespace: langfuse
  labels:
    app: langfuse
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langfuse
      component: web
  template:
    metadata:
      labels:
        app: langfuse
        component: web
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: web
          image: registry.paas/cmss/langfuse-web-custom:v0608.arm64.3
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: NEXT_PUBLIC_BASE_PATH
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: NEXT_PUBLIC_BASE_PATH
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: NEXTAUTH_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: langfuse-secrets
                  key: NEXTAUTH_SECRET
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: DATABASE_URL
            - name: DIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: DIRECT_URL
            - name: SALT
              valueFrom:
                secretKeyRef:
                  name: langfuse-secrets
                  key: SALT
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: langfuse-secrets
                  key: ENCRYPTION_KEY
            - name: TELEMETRY_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: TELEMETRY_ENABLED
            - name: LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES
            - name: CLICKHOUSE_MIGRATION_URL
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: CLICKHOUSE_MIGRATION_URL
            - name: CLICKHOUSE_URL
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: CLICKHOUSE_URL
            - name: CLICKHOUSE_USER
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: langfuse-secrets
                  key: CLICKHOUSE_PASSWORD
            - name: CLICKHOUSE_CLUSTER_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: CLICKHOUSE_CLUSTER_ENABLED
            - name: LANGFUSE_USE_AZURE_BLOB
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_USE_AZURE_BLOB
            - name: LANGFUSE_S3_EVENT_UPLOAD_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_S3_EVENT_UPLOAD_BUCKET
            - name: LANGFUSE_USE_LOCAL_FILE_STORAGE
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_USE_LOCAL_FILE_STORAGE
            - name: LANGFUSE_LOCAL_STORAGE_PATH
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_LOCAL_STORAGE_PATH
            - name: LANGFUSE_LOCAL_STORAGE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_LOCAL_STORAGE_BASE_URL
            - name: LANGFUSE_INGESTION_QUEUE_DELAY_MS
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_INGESTION_QUEUE_DELAY_MS
            - name: LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: REDIS_PORT
            - name: REDIS_AUTH
              valueFrom:
                secretKeyRef:
                  name: langfuse-secrets
                  key: REDIS_AUTH
            - name: REDIS_TLS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: REDIS_TLS_ENABLED
            - name: EMAIL_FROM_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: EMAIL_FROM_ADDRESS
            - name: SMTP_CONNECTION_URL
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: SMTP_CONNECTION_URL
            - name: EXTERNAL_AUTH_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: EXTERNAL_AUTH_ENABLED
            - name: EXTERNAL_AUTH_VALIDATE_URL
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: EXTERNAL_AUTH_VALIDATE_URL
            - name: EXTERNAL_AUTH_ACCESS_TOKEN_COOKIE
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: EXTERNAL_AUTH_ACCESS_TOKEN_COOKIE
            - name: EXTERNAL_AUTH_LOGIN_REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: EXTERNAL_AUTH_LOGIN_REDIRECT_URL
            - name: NEXT_PUBLIC_EXTERNAL_AUTH_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: NEXT_PUBLIC_EXTERNAL_AUTH_ENABLED
            - name: NEXT_PUBLIC_EXTERNAL_AUTH_LOGIN_REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: NEXT_PUBLIC_EXTERNAL_AUTH_LOGIN_REDIRECT_URL
            - name: LANGFUSE_DEFAULT_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_DEFAULT_PROJECT_ID
            - name: LANGFUSE_DEFAULT_PROJECT_ROLE
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_DEFAULT_PROJECT_ROLE
            - name: EXTERNAL_AUTH_VALIDATION_MODE
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: EXTERNAL_AUTH_VALIDATION_MODE
            - name: NEXT_PUBLIC_EXTERNAL_AUTH_VALIDATION_MODE
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: NEXT_PUBLIC_EXTERNAL_AUTH_VALIDATION_MODE
            - name: NEXT_PUBLIC_EXTERNAL_AUTH_ACCESS_TOKEN_COOKIE
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: NEXT_PUBLIC_EXTERNAL_AUTH_ACCESS_TOKEN_COOKIE
            - name: LANGFUSE_INIT_ORG_ID
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_INIT_ORG_ID
            - name: LANGFUSE_INIT_ORG_NAME
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_INIT_ORG_NAME
            - name: LANGFUSE_INIT_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_INIT_PROJECT_ID
            - name: LANGFUSE_INIT_PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_INIT_PROJECT_NAME
            - name: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
            - name: LANGFUSE_INIT_PROJECT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_INIT_PROJECT_SECRET_KEY
            - name: LANGFUSE_INIT_USER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_INIT_USER_EMAIL
            - name: LANGFUSE_INIT_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_INIT_USER_NAME
            - name: LANGFUSE_INIT_USER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: langfuse-config
                  key: LANGFUSE_INIT_USER_PASSWORD
          
          volumeMounts:
            - name: langfuse-storage
              mountPath: /app/langfuse-storage
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: timezone
              mountPath: /etc/timezone
              readOnly: true
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
      volumes:
        - name: langfuse-storage
          persistentVolumeClaim:
            claimName: langfuse-storage-pvc
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: timezone
          hostPath:
            path: /etc/timezone
            type: File

---
apiVersion: v1
kind: Service
metadata:
  name: langfuse-web
  namespace: langfuse
  labels:
    app: langfuse
    component: web
spec:
  type: ClusterIP
  selector:
    app: langfuse
    component: web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
