apiVersion: v1
kind: ConfigMap
metadata:
  name: langfuse-config
  namespace: langfuse
data:
  # 基础配置
  NEXT_PUBLIC_BASE_PATH: "/langfuse"
  NEXTAUTH_URL: "https://10.151.18.110:31987/langfuse"
  NEXTAUTH_SECRET: "mysecret"

  # 数据库配置
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
  DIRECT_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
  SALT: "mysalt"
  ENCRYPTION_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
  TELEMETRY_ENABLED: "true"
  LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: "true"

  # ClickHouse 配置 - 使用宿主机上安装的 ClickHouse
  # 注意：请将 clickhouse://YOUR_HOST_IP:port 中的 YOUR_HOST_IP 替换为实际的宿主机 IP 地址，默认10.151.18.110
  # 可通过命令获取：ip route get 1 | awk '{print $7}' | head -1
  CLICKHOUSE_MIGRATION_URL: "clickhouse://10.151.18.110:9000"
  CLICKHOUSE_URL: "http://10.151.18.110:8123"
  CLICKHOUSE_USER: "default"
  CLICKHOUSE_CLUSTER_ENABLED: "false"

  # 本地文件存储配置
  LANGFUSE_USE_AZURE_BLOB: "false"
  LANGFUSE_S3_EVENT_UPLOAD_BUCKET: "langfuse"
  LANGFUSE_USE_LOCAL_FILE_STORAGE: "true"
  LANGFUSE_LOCAL_STORAGE_PATH: "/app/langfuse-storage"
  LANGFUSE_LOCAL_STORAGE_BASE_URL: "https://10.151.18.110:31987/langfuse/api/public/files"

  # 队列配置
  LANGFUSE_INGESTION_QUEUE_DELAY_MS: ""
  LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS: ""

  # Redis 配置
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_AUTH: "myredissecret"
  REDIS_TLS_ENABLED: "false"

  # 邮件配置
  EMAIL_FROM_ADDRESS: ""
  SMTP_CONNECTION_URL: ""

  # External auth bridge
  EXTERNAL_AUTH_ENABLED: "true"
  EXTERNAL_AUTH_VALIDATE_URL: "http://aiops-ai-backend-service-svc.infra.svc.cluster.local:80/internal/auth/validate"
  EXTERNAL_AUTH_ACCESS_TOKEN_COOKIE: "access_token"
  EXTERNAL_AUTH_LOGIN_REDIRECT_URL: "https://10.151.18.110:31987/"
  NEXT_PUBLIC_EXTERNAL_AUTH_ENABLED: "true"
  NEXT_PUBLIC_EXTERNAL_AUTH_LOGIN_REDIRECT_URL: "https://10.151.18.110:31987/"
  LANGFUSE_DEFAULT_PROJECT_ID: "cmk0uyvyj0006pk07ml635l8g"
  LANGFUSE_DEFAULT_PROJECT_ROLE: "VIEWER"
  EXTERNAL_AUTH_VALIDATION_MODE: "per_request"
  NEXT_PUBLIC_EXTERNAL_AUTH_VALIDATION_MODE: "per_request"
  NEXT_PUBLIC_EXTERNAL_AUTH_ACCESS_TOKEN_COOKIE: "access_token"

  # 初始化配置
  LANGFUSE_INIT_ORG_ID: "cmpdsy6qk0000udwobojvitba"
  LANGFUSE_INIT_ORG_NAME: "llm-test-001"
  LANGFUSE_INIT_PROJECT_ID: "cmk0uyvyj0006pk07ml635l8g"
  LANGFUSE_INIT_PROJECT_NAME: "llm-agent"
  LANGFUSE_INIT_PROJECT_PUBLIC_KEY: "pk-lf-acc3323c-20d0-4d0e-bd0d-b259d2708152"
  LANGFUSE_INIT_PROJECT_SECRET_KEY: "sk-lf-fb3e287e-d635-4582-8752-df63bdaf9f08"
  LANGFUSE_INIT_USER_EMAIL: "admin2@example.com"
  LANGFUSE_INIT_USER_NAME: "admin2"
  LANGFUSE_INIT_USER_PASSWORD: "R9eDuck$!mpleM00n1"

  # PostgreSQL 配置
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "postgres"
  TZ: "UTC"
  PGTZ: "UTC"
